const data=[
     
     { 
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRV7ckKDkJLCBxNeaubEtT-uIbVB3ykRNJL4A&usqp=CAU",
      id:1,
     prod:"Boat Earbuds",
     price:'Rs.1500',
     Qty:1
    },
    {    img:"https://5.imimg.com/data5/SELLER/Default/2022/12/TX/VE/BW/160157174/50-inch-television-250x250.jpeg",
           id:2,
        prod:"Mi 32inch Television",
        price:'Rs.30,000',
        Qty:1
    },
     {   id:3,
        prod:"All in one Mixer-juicer",
        price:'Rs.12000',
        Qty:1,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBzZkd_k-_lTqQuIWE5O1Ec99JXhReBDF1jQ&usqp=CAU",
       },
       {   id:4,
           prod:"Samsung Galaxy",
           price:'Rs.29000',
           Qty:1,
           img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjIqlZs6siFvmjmsaAzRZ5jbnRGVx5EtyMqw&usqp=CAU",
       },
       {  
        id:5,
       prod:"Refridgerator",
       price:'Rs.15000',
       Qty:1,
       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR49P97J50zj9ybxtFnPJ6ZowV4RWXtyqGkcA&usqp=CAU",
      },
      {    id:6,
          prod:"Microwave Oven",
          price:'Rs.20,000',
          Qty:1,
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzc1j2dwfIRcCKrC1EU2wYYJeGortylaDAeQ&usqp=CAU",
      },
       {   id:7,
          prod:"Noise Headphones",
          price:'Rs.2000',
          Qty:1,
          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUHev07IU1vNS527rWOLJfCmB1E625r-VL0w&usqp=CAU",
         },
         {    id:8,
            prod:"Chroma 42-inch Television",
            price:'Rs.39,000',
            Qty:1,
            img:"https://5.imimg.com/data5/QT/CY/XQ/SELLER-48740806/full-hd-smart-tv-500x500.jpeg",
        },
         {   id:9,
            prod:"Redmi Node-10",
            price:'Rs.19,000',
            Qty:1,
            img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOsScZvydQjDkAurlJBTQkxsMsPFeZ9OkCvA&usqp=CAU",
           }
    
];
export default data;